name: Hello from meshStack

on:
  workflow_dispatch:
    inputs:
      buildingBlockRun:
        description: "meshStack Building Block Run"
        required: true
     
jobs:
  say-hello:
    runs-on: visa

    steps:
      - name: Say Hello
        run: |
          echo "ğŸ‘‹ Hello from meshStack!"
          echo "ğŸ—ï¸ Building Block Run: ${{ inputs.buildingBlockRun }}"
